### ISSUE TITLE
GPAW notebooks fails 

### ISSUE THREAD

**Issue by jan-janssen** [pyiron/docker-stacks#21]
```
[NbConvertApp] Converting notebook /home/pyiron/energy_volume_curve.ipynb to notebook
1185[NbConvertApp] Executing notebook with kernel: python3
1186Traceback (most recent call last):
1187  File "/opt/conda/bin/jupyter-nbconvert", line 11, in <module>
1188    sys.exit(main())
1189  File "/opt/conda/lib/python3.8/site-packages/jupyter_core/application.py", line 270, in launch_instance
1190    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
1191  File "/opt/conda/lib/python3.8/site-packages/traitlets/config/application.py", line 837, in launch_instance
1192    app.start()
1193  File "/opt/conda/lib/python3.8/site-packages/nbconvert/nbconvertapp.py", line 350, in start
1194    self.convert_notebooks()
1195  File "/opt/conda/lib/python3.8/site-packages/nbconvert/nbconvertapp.py", line 524, in convert_notebooks
1196    self.convert_single_notebook(notebook_filename)
1197  File "/opt/conda/lib/python3.8/site-packages/nbconvert/nbconvertapp.py", line 489, in convert_single_notebook
1198    output, resources = self.export_single_notebook(notebook_filename, resources, input_buffer=input_buffer)
1199  File "/opt/conda/lib/python3.8/site-packages/nbconvert/nbconvertapp.py", line 418, in export_single_notebook
1200    output, resources = self.exporter.from_filename(notebook_filename, resources=resources)
1201  File "/opt/conda/lib/python3.8/site-packages/nbconvert/exporters/exporter.py", line 181, in from_filename
1202    return self.from_file(f, resources=resources, **kw)
1203  File "/opt/conda/lib/python3.8/site-packages/nbconvert/exporters/exporter.py", line 199, in from_file
1204    return self.from_notebook_node(nbformat.read(file_stream, as_version=4), resources=resources, **kw)
1205  File "/opt/conda/lib/python3.8/site-packages/nbconvert/exporters/notebook.py", line 32, in from_notebook_node
1206    nb_copy, resources = super().from_notebook_node(nb, resources, **kw)
1207  File "/opt/conda/lib/python3.8/site-packages/nbconvert/exporters/exporter.py", line 143, in from_notebook_node
1208    nb_copy, resources = self._preprocess(nb_copy, resources)
1209  File "/opt/conda/lib/python3.8/site-packages/nbconvert/exporters/exporter.py", line 318, in _preprocess
1210    nbc, resc = preprocessor(nbc, resc)
1211  File "/opt/conda/lib/python3.8/site-packages/nbconvert/preprocessors/base.py", line 47, in __call__
1212    return self.preprocess(nb, resources)
1213  File "/opt/conda/lib/python3.8/site-packages/nbconvert/preprocessors/execute.py", line 79, in preprocess
1214    self.execute()
1215  File "/opt/conda/lib/python3.8/site-packages/nbclient/util.py", line 74, in wrapped
1216    return just_run(coro(*args, **kwargs))
1217  File "/opt/conda/lib/python3.8/site-packages/nbclient/util.py", line 53, in just_run
1218    return loop.run_until_complete(coro)
1219  File "/opt/conda/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
1220    return future.result()
1221  File "/opt/conda/lib/python3.8/site-packages/nbclient/client.py", line 535, in async_execute
1222    await self.async_execute_cell(
1223  File "/opt/conda/lib/python3.8/site-packages/nbconvert/preprocessors/execute.py", line 123, in async_execute_cell
1224    cell, resources = self.preprocess_cell(cell, self.resources, cell_index)
1225  File "/opt/conda/lib/python3.8/site-packages/nbconvert/preprocessors/execute.py", line 146, in preprocess_cell
1226    cell = run_sync(NotebookClient.async_execute_cell)(self, cell, index, store_history=self.store_history)
1227  File "/opt/conda/lib/python3.8/site-packages/nbclient/util.py", line 74, in wrapped
1228    return just_run(coro(*args, **kwargs))
1229  File "/opt/conda/lib/python3.8/site-packages/nbclient/util.py", line 53, in just_run
1230    return loop.run_until_complete(coro)
1231  File "/opt/conda/lib/python3.8/site-packages/nest_asyncio.py", line 95, in run_until_complete
1232    return f.result()
1233  File "/opt/conda/lib/python3.8/asyncio/futures.py", line 178, in result
1234    raise self._exception
1235  File "/opt/conda/lib/python3.8/asyncio/tasks.py", line 280, in __step
1236    result = coro.send(None)
1237  File "/opt/conda/lib/python3.8/site-packages/nbclient/client.py", line 827, in async_execute_cell
1238    self._check_raise_for_error(cell, exec_reply)
1239  File "/opt/conda/lib/python3.8/site-packages/nbclient/client.py", line 735, in _check_raise_for_error
1240    raise CellExecutionError.from_cell_and_msg(cell, exec_reply['content'])
1241nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
1242------------------
1243for strain in np.linspace(0.95, 1.05, 7):
1244    strain_str = str(strain).replace('.', '_')
1245    job_vasp_strain = pr.create_job(job_type=pr.job_type.Gpaw, job_name='gpaw_' + strain_str)
1246    job_vasp_strain.set_encut(320.0)
1247    job_vasp_strain.structure = basis.copy()
1248    job_vasp_strain.structure.set_cell(cell=basis.cell * strain ** (1/3), scale_atoms=True)
1249    job_vasp_strain.run()
1250------------------
1251
1252---------------------------------------------------------------------------
1253RuntimeError                              Traceback (most recent call last)
1254<ipython-input-1-938fbdfb8715> in <module>
1255      5     job_vasp_strain.structure = basis.copy()
1256      6     job_vasp_strain.structure.set_cell(cell=basis.cell * strain ** (1/3), scale_atoms=True)
1257----> 7     job_vasp_strain.run()
1258
1259/opt/conda/lib/python3.8/site-packages/pyiron_base/job/generic.py in run(self, delete_existing_job, repair, debug, run_mode, run_again)
1260    682                 status = "created"
1261    683             if status == "initialized":
1262--> 684                 self._run_if_new(debug=debug)
1263    685             elif status == "created":
1264    686                 que_id = self._run_if_created()
1265
1266/opt/conda/lib/python3.8/site-packages/pyiron_base/job/generic.py in _run_if_new(self, debug)
1267   1392         else:
1268   1393             self.save()
1269-> 1394             self.run()
1270   1395 
1271   1396     def _run_if_created(self):
1272
1273/opt/conda/lib/python3.8/site-packages/pyiron_base/job/generic.py in run(self, delete_existing_job, repair, debug, run_mode, run_again)
1274    684                 self._run_if_new(debug=debug)
1275    685             elif status == "created":
1276--> 686                 que_id = self._run_if_created()
1277    687                 if que_id:
1278    688                     self._logger.info(
1279
1280/opt/conda/lib/python3.8/site-packages/pyiron_base/job/generic.py in _run_if_created(self)
1281   1409             self.run_if_manually()
1282   1410         elif self.server.run_mode.modal:
1283-> 1411             self.run_static()
1284   1412         elif self.server.run_mode.non_modal or self.server.run_mode.thread:
1285   1413             self.run_if_non_modal()
1286
1287/opt/conda/lib/python3.8/site-packages/pyiron/gpaw/gpaw.py in run_static(self)
1288    152         pre_run_mode = self.server.run_mode
1289    153         self.server.run_mode.interactive = True
1290--> 154         self.run_if_interactive()
1291    155         self.interactive_close()
1292    156         self.server.run_mode = pre_run_mode
1293
1294/opt/conda/lib/python3.8/site-packages/pyiron/gpaw/gpaw.py in run_if_interactive(self)
1295    177             self.structure.set_calculator(calc)
1296    178         self.status.running = True
1297--> 179         self.structure.calc.calculate(self.structure)
1298    180         self.interactive_collect()
1299    181 
1300
1301/opt/conda/lib/python3.8/site-packages/gpaw/calculator.py in calculate(self, atoms, properties, system_changes)
1302    282                 self.hamiltonian = None
1303    283                 self.scf = None
1304--> 284                 self.initialize(atoms)
1305    285 
1306    286             self.set_positions(atoms)
1307
1308/opt/conda/lib/python3.8/site-packages/gpaw/calculator.py in initialize(self, atoms, reading)
1309    555         realspace = (mode.name != 'pw' and mode.interpolation != 'fft')
1310    556 
1311--> 557         self.create_setups(mode, xc)
1312    558 
1313    559         if not realspace:
1314
1315/opt/conda/lib/python3.8/site-packages/gpaw/calculator.py in create_setups(self, mode, xc)
1316    779 
1317    780         Z_a = self.atoms.get_atomic_numbers()
1318--> 781         self.setups = Setups(Z_a,
1319    782                              self.parameters.setups, self.parameters.basis,
1320    783                              xc, filter, self.world)
1321
1322/opt/conda/lib/python3.8/site-packages/gpaw/setup.py in __init__(self, Z_a, setup_types, basis_sets, xc, filter, world)
1323   1358                 if isinstance(basis, basestring):
1324   1359                     basis = Basis(symbol, basis, world=world)
1325-> 1360                 setup = create_setup(symbol, xc, 2, type,
1326   1361                                      basis, setupdata=setupdata,
1327   1362                                      filter=filter, world=world)
1328
1329/opt/conda/lib/python3.8/site-packages/gpaw/setup.py in create_setup(symbol, xc, lmax, type, basis, setupdata, filter, world)
1330     84                                  'the %s functional.' % xc.get_setup_name())
1331     85         else:
1332---> 86             setupdata = SetupData(symbol, xc.get_setup_name(),
1333     87                                   type, True,
1334     88                                   world=world)
1335
1336/opt/conda/lib/python3.8/site-packages/gpaw/setup_data.py in __init__(self, symbol, xcsetupname, name, readxml, zero_reference, world, generator_version)
1337    120 
1338    121         if readxml:
1339--> 122             self.read_xml(world=world)
1340    123 
1341    124     def __repr__(self):
1342
1343/opt/conda/lib/python3.8/site-packages/gpaw/setup_data.py in read_xml(self, source, world)
1344    138 
1345    139     def read_xml(self, source=None, world=None):
1346--> 140         PAWXMLParser(self).parse(source=source, world=world)
1347    141         nj = len(self.l_j)
1348    142         self.e_kin_jj.shape = (nj, nj)
1349
1350/opt/conda/lib/python3.8/site-packages/gpaw/setup_data.py in parse(self, source, world)
1351    436         setup = self.setup
1352    437         if source is None:
1353--> 438             setup.filename, source = search_for_file(setup.stdfilename, world)
1354    439 
1355    440         setup.fingerprint = hashlib.md5(source).hexdigest()
1356
1357/opt/conda/lib/python3.8/site-packages/gpaw/setup_data.py in search_for_file(name, world)
1358    421 https://wiki.fysik.dtu.dk/gpaw/install.html#install-paw-datasets
1359    422 for details."""
1360--> 423         raise RuntimeError('%s\n%s' % (err, helpful_message))
1361    424 
1362    425     return filename, source
1363
1364RuntimeError: Could not find required PAW dataset file "Fe.PBE".
1365
1366You need to set the GPAW_SETUP_PATH environment variable to point to
1367the directories where PAW dataset and basis files are stored.  See
1368https://wiki.fysik.dtu.dk/gpaw/install.html#install-paw-datasets
1369for details.
1370RuntimeError: Could not find required PAW dataset file "Fe.PBE".
1371
1372You need to set the GPAW_SETUP_PATH environment variable to point to
1373the directories where PAW dataset and basis files are stored.  See
1374https://wiki.fysik.dtu.dk/gpaw/install.html#install-paw-datasets
1375for details.
1376
1377
````

**Comment by jan-janssen** [comment]
```
[NbConvertApp] Converting notebook /home/pyiron/test_pyiron_installation.ipynb to notebook
1396[NbConvertApp] Executing notebook with kernel: python3
1397Traceback (most recent call last):
1398  File "/opt/conda/bin/jupyter-nbconvert", line 11, in <module>
1399    sys.exit(main())
1400  File "/opt/conda/lib/python3.8/site-packages/jupyter_core/application.py", line 270, in launch_instance
1401    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
1402  File "/opt/conda/lib/python3.8/site-packages/traitlets/config/application.py", line 837, in launch_instance
1403    app.start()
1404  File "/opt/conda/lib/python3.8/site-packages/nbconvert/nbconvertapp.py", line 350, in start
1405    self.convert_notebooks()
1406  File "/opt/conda/lib/python3.8/site-packages/nbconvert/nbconvertapp.py", line 524, in convert_notebooks
1407    self.convert_single_notebook(notebook_filename)
1408  File "/opt/conda/lib/python3.8/site-packages/nbconvert/nbconvertapp.py", line 489, in convert_single_notebook
1409    output, resources = self.export_single_notebook(notebook_filename, resources, input_buffer=input_buffer)
1410  File "/opt/conda/lib/python3.8/site-packages/nbconvert/nbconvertapp.py", line 418, in export_single_notebook
1411    output, resources = self.exporter.from_filename(notebook_filename, resources=resources)
1412  File "/opt/conda/lib/python3.8/site-packages/nbconvert/exporters/exporter.py", line 181, in from_filename
1413    return self.from_file(f, resources=resources, **kw)
1414  File "/opt/conda/lib/python3.8/site-packages/nbconvert/exporters/exporter.py", line 199, in from_file
1415    return self.from_notebook_node(nbformat.read(file_stream, as_version=4), resources=resources, **kw)
1416  File "/opt/conda/lib/python3.8/site-packages/nbconvert/exporters/notebook.py", line 32, in from_notebook_node
1417    nb_copy, resources = super().from_notebook_node(nb, resources, **kw)
1418  File "/opt/conda/lib/python3.8/site-packages/nbconvert/exporters/exporter.py", line 143, in from_notebook_node
1419    nb_copy, resources = self._preprocess(nb_copy, resources)
1420  File "/opt/conda/lib/python3.8/site-packages/nbconvert/exporters/exporter.py", line 318, in _preprocess
1421    nbc, resc = preprocessor(nbc, resc)
1422  File "/opt/conda/lib/python3.8/site-packages/nbconvert/preprocessors/base.py", line 47, in __call__
1423    return self.preprocess(nb, resources)
1424  File "/opt/conda/lib/python3.8/site-packages/nbconvert/preprocessors/execute.py", line 79, in preprocess
1425    self.execute()
1426  File "/opt/conda/lib/python3.8/site-packages/nbclient/util.py", line 74, in wrapped
1427    return just_run(coro(*args, **kwargs))
1428  File "/opt/conda/lib/python3.8/site-packages/nbclient/util.py", line 53, in just_run
1429    return loop.run_until_complete(coro)
1430  File "/opt/conda/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
1431    return future.result()
1432  File "/opt/conda/lib/python3.8/site-packages/nbclient/client.py", line 535, in async_execute
1433    await self.async_execute_cell(
1434  File "/opt/conda/lib/python3.8/site-packages/nbconvert/preprocessors/execute.py", line 123, in async_execute_cell
1435    cell, resources = self.preprocess_cell(cell, self.resources, cell_index)
1436  File "/opt/conda/lib/python3.8/site-packages/nbconvert/preprocessors/execute.py", line 146, in preprocess_cell
1437    cell = run_sync(NotebookClient.async_execute_cell)(self, cell, index, store_history=self.store_history)
1438  File "/opt/conda/lib/python3.8/site-packages/nbclient/util.py", line 74, in wrapped
1439    return just_run(coro(*args, **kwargs))
1440  File "/opt/conda/lib/python3.8/site-packages/nbclient/util.py", line 53, in just_run
1441    return loop.run_until_complete(coro)
1442  File "/opt/conda/lib/python3.8/site-packages/nest_asyncio.py", line 95, in run_until_complete
1443    return f.result()
1444  File "/opt/conda/lib/python3.8/asyncio/futures.py", line 178, in result
1445    raise self._exception
1446  File "/opt/conda/lib/python3.8/asyncio/tasks.py", line 280, in __step
1447    result = coro.send(None)
1448  File "/opt/conda/lib/python3.8/site-packages/nbclient/client.py", line 827, in async_execute_cell
1449    self._check_raise_for_error(cell, exec_reply)
1450  File "/opt/conda/lib/python3.8/site-packages/nbclient/client.py", line 735, in _check_raise_for_error
1451    raise CellExecutionError.from_cell_and_msg(cell, exec_reply['content'])
1452nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
1453------------------
1454from pyiron import Project
1455pr = Project('gpaw')
1456lmp = pr.create_job(pr.job_type.Gpaw, 'static')
1457lmp.structure = pr.create_structure('Fe', 'bcc', 2.55)
1458lmp.run()  # The job static was saved and received the ID: 3
1459------------------
1460
1461---------------------------------------------------------------------------
1462RuntimeError                              Traceback (most recent call last)
1463<ipython-input-1-59a973bd2305> in <module>
1464      3 lmp = pr.create_job(pr.job_type.Gpaw, 'static')
1465      4 lmp.structure = pr.create_structure('Fe', 'bcc', 2.55)
1466----> 5 lmp.run()  # The job static was saved and received the ID: 3
1467
1468/opt/conda/lib/python3.8/site-packages/pyiron_base/job/generic.py in run(self, delete_existing_job, repair, debug, run_mode, run_again)
1469    682                 status = "created"
1470    683             if status == "initialized":
1471--> 684                 self._run_if_new(debug=debug)
1472    685             elif status == "created":
1473    686                 que_id = self._run_if_created()
1474
1475/opt/conda/lib/python3.8/site-packages/pyiron_base/job/generic.py in _run_if_new(self, debug)
1476   1392         else:
1477   1393             self.save()
1478-> 1394             self.run()
1479   1395 
1480   1396     def _run_if_created(self):
1481
1482/opt/conda/lib/python3.8/site-packages/pyiron_base/job/generic.py in run(self, delete_existing_job, repair, debug, run_mode, run_again)
1483    684                 self._run_if_new(debug=debug)
1484    685             elif status == "created":
1485--> 686                 que_id = self._run_if_created()
1486    687                 if que_id:
1487    688                     self._logger.info(
1488
1489/opt/conda/lib/python3.8/site-packages/pyiron_base/job/generic.py in _run_if_created(self)
1490   1409             self.run_if_manually()
1491   1410         elif self.server.run_mode.modal:
1492-> 1411             self.run_static()
1493   1412         elif self.server.run_mode.non_modal or self.server.run_mode.thread:
1494   1413             self.run_if_non_modal()
1495
1496/opt/conda/lib/python3.8/site-packages/pyiron/gpaw/gpaw.py in run_static(self)
1497    152         pre_run_mode = self.server.run_mode
1498    153         self.server.run_mode.interactive = True
1499--> 154         self.run_if_interactive()
1500    155         self.interactive_close()
1501    156         self.server.run_mode = pre_run_mode
1502
1503/opt/conda/lib/python3.8/site-packages/pyiron/gpaw/gpaw.py in run_if_interactive(self)
1504    177             self.structure.set_calculator(calc)
1505    178         self.status.running = True
1506--> 179         self.structure.calc.calculate(self.structure)
1507    180         self.interactive_collect()
1508    181 
1509
1510/opt/conda/lib/python3.8/site-packages/gpaw/calculator.py in calculate(self, atoms, properties, system_changes)
1511    282                 self.hamiltonian = None
1512    283                 self.scf = None
1513--> 284                 self.initialize(atoms)
1514    285 
1515    286             self.set_positions(atoms)
1516
1517/opt/conda/lib/python3.8/site-packages/gpaw/calculator.py in initialize(self, atoms, reading)
1518    555         realspace = (mode.name != 'pw' and mode.interpolation != 'fft')
1519    556 
1520--> 557         self.create_setups(mode, xc)
1521    558 
1522    559         if not realspace:
1523
1524/opt/conda/lib/python3.8/site-packages/gpaw/calculator.py in create_setups(self, mode, xc)
1525    779 
1526    780         Z_a = self.atoms.get_atomic_numbers()
1527--> 781         self.setups = Setups(Z_a,
1528    782                              self.parameters.setups, self.parameters.basis,
1529    783                              xc, filter, self.world)
1530
1531/opt/conda/lib/python3.8/site-packages/gpaw/setup.py in __init__(self, Z_a, setup_types, basis_sets, xc, filter, world)
1532   1358                 if isinstance(basis, basestring):
1533   1359                     basis = Basis(symbol, basis, world=world)
1534-> 1360                 setup = create_setup(symbol, xc, 2, type,
1535   1361                                      basis, setupdata=setupdata,
1536   1362                                      filter=filter, world=world)
1537
1538/opt/conda/lib/python3.8/site-packages/gpaw/setup.py in create_setup(symbol, xc, lmax, type, basis, setupdata, filter, world)
1539     84                                  'the %s functional.' % xc.get_setup_name())
1540     85         else:
1541---> 86             setupdata = SetupData(symbol, xc.get_setup_name(),
1542     87                                   type, True,
1543     88                                   world=world)
1544
1545/opt/conda/lib/python3.8/site-packages/gpaw/setup_data.py in __init__(self, symbol, xcsetupname, name, readxml, zero_reference, world, generator_version)
1546    120 
1547    121         if readxml:
1548--> 122             self.read_xml(world=world)
1549    123 
1550    124     def __repr__(self):
1551
1552/opt/conda/lib/python3.8/site-packages/gpaw/setup_data.py in read_xml(self, source, world)
1553    138 
1554    139     def read_xml(self, source=None, world=None):
1555--> 140         PAWXMLParser(self).parse(source=source, world=world)
1556    141         nj = len(self.l_j)
1557    142         self.e_kin_jj.shape = (nj, nj)
1558
1559/opt/conda/lib/python3.8/site-packages/gpaw/setup_data.py in parse(self, source, world)
1560    436         setup = self.setup
1561    437         if source is None:
1562--> 438             setup.filename, source = search_for_file(setup.stdfilename, world)
1563    439 
1564    440         setup.fingerprint = hashlib.md5(source).hexdigest()
1565
1566/opt/conda/lib/python3.8/site-packages/gpaw/setup_data.py in search_for_file(name, world)
1567    421 https://wiki.fysik.dtu.dk/gpaw/install.html#install-paw-datasets
1568    422 for details."""
1569--> 423         raise RuntimeError('%s\n%s' % (err, helpful_message))
1570    424 
1571    425     return filename, source
1572
1573RuntimeError: Could not find required PAW dataset file "Fe.PBE".
1574
1575You need to set the GPAW_SETUP_PATH environment variable to point to
1576the directories where PAW dataset and basis files are stored.  See
1577https://wiki.fysik.dtu.dk/gpaw/install.html#install-paw-datasets
1578for details.
1579RuntimeError: Could not find required PAW dataset file "Fe.PBE".
1580
1581You need to set the GPAW_SETUP_PATH environment variable to point to
1582the directories where PAW dataset and basis files are stored.  See
1583https://wiki.fysik.dtu.dk/gpaw/install.html#install-paw-datasets
1584for details.
1585
1586```
