### ISSUE TITLE
DAMASK example 

### ISSUE THREAD

**Issue by jan-janssen** [pyiron/docker-stacks#32]
@muh-hassani Can you add the notebook from Vitesh? https://github.com/vitesh13/DAMASK_workflows/blob/master/DAMASK_WORKFLOWS.ipynb and the required example files these are available at https://github.com/vitesh13/DAMASK_workflows/tree/master/Examples In addition the notebook also requires two more python modules https://github.com/vitesh13/DAMASK_workflows/blob/master/Plot_stress_strain.py and https://github.com/vitesh13/DAMASK_workflows/blob/master/simulation_runner.py . I created a cleaned up fork of the repository here https://github.com/matbinder/DAMASK-example so either you can use this or fork it to your account to add the elastic constant example to demonstrate the combined workflow of LAMMPS and DAMASK.

**Comment by muh-hassani** [comment]
Already in the image, I have included the example from Vitesh. In `damask/include_notebooks.sh`:  
```
git clone https://github.com/vitesh13/DAMASK_workflows
cp -r "$HOME"/DAMASK_workflows/DAMASK_workflows.ipynb "$HOME"/
```  
And in `.travis.yml` the notebook is tested via:
```
docker run --rm pyiron/damask /bin/bash -c 'source /opt/conda/bin/activate; i=0; for f in $(ls ~/*.ipynb); do jupyter nbconvert --ExecutePreprocessor.timeout=9999999 --to notebook --execute $f || i=$((i+1)); done; if [ $i -gt 0 ]; then exit 1; fi;'
```  
I can change the source of this to [https://github.com/matbinder/DAMASK-example](https://github.com/matbinder/DAMASK-example). But is this sufficient? I also applied the postBuild script you had in the binder directory.

**Comment by muh-hassani** [comment]
@jan-janssen can you please check `damask/include_notebooks.sh `. I have included the repository you mentioned, and the build and tests were successful.

**Comment by jan-janssen** [comment]
In the output of the test it says:
```
0.82s$ docker run --rm pyiron/damask /bin/bash -c 'source /opt/conda/bin/activate; i=0; for f in $(ls ~/*.ipynb); do jupyter nbconvert --ExecutePreprocessor.timeout=9999999 --to notebook --execute $f || i=$((i+1)); done; if [ $i -gt 0 ]; then exit 1; fi;'
1671ls: cannot access '/home/pyiron/*.ipynb': No such file or directory
1672The command "docker run --rm pyiron/damask /bin/bash -c 'source /opt/conda/bin/activate; i=0; for f in $(ls ~/*.ipynb); do jupyter nbconvert --ExecutePreprocessor.timeout=9999999 --to notebook --execute $f || i=$((i+1)); done; if [ $i -gt 0 ]; then exit 1; fi;'" exited with 0.
```
So it does not find the notebooks for DAMASK.

**Comment by muh-hassani** [comment]
Thanks for pointing this out. The problem is in the build. When the postBuild script runs, it fails and include_notebooks.sh is not even called. I paste below the error:
```
Cloning into 'DAMASK'...

Note: switching to '264fab44'.

You are in 'detached HEAD' state. You can look around, make experimental

changes and commit them, and you can discard any commits you make in this

state without impacting any branches by switching back to a branch.

If you want to create a new branch to retain commits you create, you may

do so (now or later) by using -c with the switch command. Example:

  git switch -c <new-branch-name>

Or undo this operation with:

  git switch -

Turn off this advice by setting config variable advice.detachedHead to false

HEAD is now at 264fab44 [skip ci] updated version information after successful test of v3.0.0-alpha-482-g846cbdd2e

/home/pyiron/postBuild: line 8: patch: command not found

WARNING: The directory '/home/pyiron/.cache/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.

Processing /home/pyiron/DAMASK/python

    ERROR: Command errored out with exit status 1:

     command: /opt/conda/bin/python3.8 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-wbulfa0a/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-wbulfa0a/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-fxqnnfmf

         cwd: /tmp/pip-req-build-wbulfa0a/

    Complete output (5 lines):

    Traceback (most recent call last):

      File "<string>", line 1, in <module>

      File "/tmp/pip-req-build-wbulfa0a/setup.py", line 5, in <module>

        with open(Path(__file__).parent/'damask/VERSION') as f:

    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-req-build-wbulfa0a/damask/VERSION'

    ----------------------------------------

ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

Cloning into 'DAMASK-example'
``` 
So I guess I need to install patch and try it again.
